# Generated by Django 5.1.4 on 2025-01-18 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='question',
            new_name='submission',
        ),
        migrations.RemoveField(
            model_name='review',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated',
        ),
    ]
