# Generated by Django 5.1.4 on 2025-01-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='game',
            field=models.TextField(choices=[('MATH', 'Math Facts'), ('ANAGRAM', 'Anagram Hunt')], default='MATH'),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='operation',
            field=models.TextField(choices=[('x', 'x'), ('/', '/'), ('-', '-'), ('+', '+'), ('n/a', 'N/A')], default='+'),
        ),
    ]
