# Generated by Django 5.1.4 on 2025-01-15 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_gamescore_game_alter_gamescore_operation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamescore',
            old_name='operation',
            new_name='operations',
        ),
    ]
