# Generated by Django 5.1.4 on 2025-01-17 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_gamescore_operations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamescore',
            name='max_number',
        ),
    ]
