# Generated by Django 5.1.4 on 2025-01-18 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reviews',
        ),
    ]
