# Generated by Django 5.1.4 on 2025-01-20 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_gamescore_max_number_gamescore_operations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamescore',
            old_name='operations',
            new_name='operation',
        ),
    ]
