# Generated by Django 5.1.4 on 2025-01-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_rename_operations_gamescore_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='operation',
            field=models.CharField(default='+', max_length=10),
        ),
    ]
