# Generated by Django 5.1.4 on 2025-01-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_gamescore_word_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='word_length',
            field=models.IntegerField(default=5),
        ),
    ]
