# Generated by Django 5.1.4 on 2025-01-20 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_alter_gamescore_word_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamescore',
            old_name='word_length',
            new_name='word_char',
        ),
    ]
