# Generated by Django 5.1.4 on 2025-01-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_rename_word_length_gamescore_word_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='word_char',
            field=models.CharField(default=5, max_length=10),
        ),
    ]
