# Generated by Django 5.1.4 on 2025-01-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_alter_gamescore_word_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='word_char',
            field=models.IntegerField(default=5),
        ),
    ]
