# Generated by Django 5.1.4 on 2025-01-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_alter_gamescore_word_char'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamescore',
            name='word_char',
        ),
    ]
